# Generated by Django 4.1.7 on 2023-03-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='cse', max_length=100),
            preserve_default=False,
        ),
    ]
